### ISSUE TITLE
Active development?

### ISSUE THREAD

**Issue by adrianlewis** [mozilla-services/loads#286]
Apart from a recent commit today, there has not been any major work on this for a year. I was wondering whether active development would resume?

**Comment by amatai** [comment]
I too am interested in finding out, if this project is under active development ? Was looking to alternative to Locust.io, though it is a great load-test tool, its not well suited for functional tests.

**Comment by ametaireau** [comment]
It's actually being rewritten, and it's hapenning here: https://github.com/loads/

**Comment by amatai** [comment]
Thanks for the pointer @ametaireau !
