### ISSUE TITLE
Loadsv1 slave failing with PyFxA build error

### ISSUE THREAD

**Issue by karlht** [mozilla-services/loads#287]
The /tmp/loads-worker.log from the slave is here: https://gist.github.com/karlht/7bc93ccd5f27d8f9a6d6

Has something changed in the PyFxA interface?

**Comment by rpappalax** [comment]
Tried installing libffi-dev, PyFxA deps on master, slaves but still getting this error:
https://gist.github.com/rpappalax/e589deb0a26160255d8c

**Comment by Natim** [comment]
It looks like PyFxA is not installed in your virtualenv., please run ``./venv/bin/pip install -U PyFxA`` in the loadtests repository.
